In [100]:
import pandas as pd
import unicodedata
arquivo1 = r"C:\Users\isabella.veras\Desktop\projetodados-main\projeto_dados\ESTABELECIMENTO.csv"
arquivo2 = r"C:\Users\isabella.veras\Desktop\projetodados-main\projeto_dados\CNAE 2(in).csv"
arquivo3 = r"C:\Users\isabella.veras\Desktop\projetodados-main\projeto_dados\MUNICIPIOS 1(in).csv"


df_est = pd.read_csv(arquivo1, encoding="latin-1", sep=";", engine="python")
df_cnae = pd.read_csv(arquivo2, encoding="utf-8-sig", sep=",")
df_municipios = pd.read_csv(arquivo3, encoding="UTF-8", sep=",")

In [126]:
df_cnae.columns = df_cnae.columns.str.strip().str.lower()
df_est.columns = df_est.columns.str.strip().str.lower()
df_municipios.columns = df_municipios.columns.str.strip().str.lower()

In [101]:
df_est = df_est.dropna(axis=1, how="all")
df_est = df_est.loc[:, ~df_est.columns.str.contains("Unnamed")]

In [102]:
print("Linhas:", df_est.shape[0])

Linhas: 49994

In [103]:
df_est.head(10)

,ï»¿raiz_cnpj,numero_estabelecimento,digito_verificador_cnpj,cnpj,tipo_estabelecimento,nome_fantasia,situacao_cadastral,data_situacao,codigo_motivo_situacao,cidade_exterior,...,complemento,bairro,cep,uf,codigo_municipio,telefone_principal,telefone_secundario,email,situacao_especial,data_situacao_especial
0,26891851,1,65,26891851/0001-65,1,PRESTADORA DE SERVICO E EMPREITEIRA BECK,8,15/06/2023,1,NaN,...,NaN,RESTINGA,91790490.0,RS,8801.0,5.132483e+09,5.132587e+09,rrcontabilidade02@gmail.com,NaN,NaN
1,26891864,1,34,26891864/0001-34,1,RR SANME,2,05/01/2017,0,NaN,...,NaN,SAO LOURENCO,82210000.0,PR,7535.0,4.133531e+09,NaN,NaN,NaN,NaN
2,26891876,1,69,26891876/0001-69,1,NaN,2,18/01/2017,0,NaN,...,QUADRA D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,26891890,1,62,26891890/0001-62,1,NaN,4,12/03/2021,63,NaN,...,NaN,AGUA BRANCA,5033002.0,SP,7107.0,1.175827e+09,NaN,faconta@gmail.com,NaN,NaN
4,26891900,1,60,26891900/0001-60,1,NaN,2,18/01/2017,0,NaN,...,NaN,VILA CARVALHO,16025255.0,SP,6155.0,1.896144e+09,NaN,contabilidade.manhattan@hotmail.com.br,NaN,NaN
5,26891913,1,39,26891913/0001-39,1,REI DO GAS,2,18/01/2017,0,NaN,...,SALA A,CENTRO,13860000.0,SP,6105.0,1.994719e+09,NaN,aguaienseescritoriocontabil@gmail.com,NaN,NaN
6,26891925,1,63,26891925/0001-63,1,KISPERQUE EMPRESARIAL,8,03/02/2017,1,NaN,...,CASA,UBERABA,81570150.0,PR,7535.0,4.195323e+09,NaN,rodrigokispergue@yahoo.com.br,NaN,NaN
7,26891936,1,43,26891936/0001-43,1,PUPPY SMILE,4,05/03/2021,63,NaN,...,SALA 03,SAUDE,4132001.0,SP,7107.0,1.122192e+09,NaN,administrativo@firstlinebrindes.com.br,NaN,NaN
8,26891949,1,12,26891949/0001-12,1,NaN,4,08/11/2023,63,NaN,...,CASA,CENTRO,73825000.0,GO,67.0,6.199356e+09,NaN,jucelya2013@yahoo.com.br,NaN,NaN
9,26891962,1,71,26891962/0001-71,1,COMA BEM,4,25/02/2021,63,NaN,...,NaN,NaN,92990000.0,RS,8423.0,5.197090e+09,NaN,ricardocarlaadriana@gmail.com,NaN,NaN

In [131]:
#Verificando a tabela do CNAE
df_cnae.head()

,codigocnae,cnae_descricao,especificidades,complementos,detalhamento_adicional,observacao
0,111301,Cultivo de arroz,NaN,NaN,NaN,NaN
1,111302,Cultivo de milho,NaN,NaN,NaN,NaN
2,111303,Cultivo de trigo,NaN,NaN,NaN,NaN
3,111399,Cultivo de outros cereais não especificados an...,NaN,NaN,NaN,NaN
4,112101,Cultivo de algodão herbáceo,NaN,NaN,NaN,NaN

In [105]:
df_municipios.head()

   CódigoMunicipio                Municipio
0                1            GUAJARA-MIRIM
1                2  ALTO ALEGRE DOS PARECIS
2                3              PORTO VELHO
3                4                  BURITIS
4                5                JI-PARANA

In [132]:
print("EST:", df_est.columns.tolist())
print("CNAE:", df_cnae.columns.tolist())
print("MUN:", df_municipios.columns.tolist())

EST: ['ï»¿raiz_cnpj', 'numero_estabelecimento', 'digito_verificador_cnpj', 'cnpj', 'tipo_estabelecimento', 'nome_fantasia', 'situacao_cadastral', 'data_situacao', 'codigo_motivo_situacao', 'cidade_exterior', 'codigo_pais', 'data_inicio_atividade', 'cnae_principal', 'cnae_secundarias', 'tipo_logadouro', 'logadouro', 'numero_endereco', 'complemento', 'bairro', 'cep', 'uf', 'codigo_municipio', 'telefone_principal', 'telefone_secundario', 'email', 'situacao_especial', 'data_situacao_especial']
CNAE: ['codigocnae', 'cnae_descricao', 'especificidades', 'complementos', 'detalhamento_adicional', 'observacao']
MUN: ['códigomunicipio', 'municipio']

In [133]:
print("Detalhamento Estabelecimento: \n ")
df_est.info(20)

Detalhamento Estabelecimento:

<class 'pandas.DataFrame'>
RangeIndex: 49994 entries, 0 to 49993
Data columns (total 27 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ï»¿raiz_cnpj             49994 non-null  int64
 1   numero_estabelecimento   49994 non-null  int64
 2   digito_verificador_cnpj  49994 non-null  int64
 3   cnpj                     49994 non-null  str
 4   tipo_estabelecimento     49994 non-null  int64
 5   nome_fantasia            20780 non-null  str
 6   situacao_cadastral       49994 non-null  int64
 7   data_situacao            49994 non-null  datetime64[us]
 8   codigo_motivo_situacao   49994 non-null  int64
 9   cidade_exterior          54 non-null     str
 10  codigo_pais              90 non-null     Int64
 11  data_inicio_atividade    49994 non-null  datetime64[us]
 12  cnae_principal           49994 non-null  int64
 13  cnae_secundarias         28332 non-null  str
 14  tipo_logadouro           49904 non-null  str
 15  logadouro                49320 non-null  str
 16  numero_endereco          49994 non-null  str
 17  complemento              21149 non-null  str
 18  bairro                   47495 non-null  str
 19  cep                      47409 non-null  Int64
 20  uf                       47499 non-null  str
 21  codigo_municipio         47499 non-null  Int64
 22  telefone_principal       47270 non-null  str
 23  telefone_secundario      2892 non-null   str
 24  email                    36193 non-null  str
 25  situacao_especial        18 non-null     str
 26  data_situacao_especial   18 non-null     datetime64[ns]
dtypes: Int64(3), datetime64[ns](1), datetime64[us](2), int64(7), str(14)
memory usage: 10.4 MB

In [108]:
df_est["cep"].dtype

dtype('float64')

In [113]:
df_est["telefone_principal"] = pd.to_numeric(
    df_est["telefone_principal"],
    errors="coerce"
).astype("Int64").astype(str)

df_est["telefone_secundario"] = pd.to_numeric(
    df_est["telefone_secundario"],
    errors="coerce"
).astype("Int64").astype(str)

In [114]:
df_est["codigo_municipio"] = df_est["codigo_municipio"].astype("Int64")
df_est['codigo_pais'] = df_est['codigo_pais'].round().astype("Int64")
df_est['cep'] = df_est['cep'].round().astype("Int64")

df_est["data_situacao_especial"] = pd.to_datetime(df_est["data_situacao_especial"], dayfirst=True, errors="coerce")
df_est["data_inicio_atividade"] = pd.to_datetime(df_est["data_inicio_atividade"], dayfirst=True, errors="coerce")
df_est["data_situacao"] = pd.to_datetime(df_est["data_situacao"], dayfirst=True, errors="coerce")

In [115]:
print(df_est["data_situacao_especial"].head())
print(df_est["data_situacao"].head())
print(df_est["data_inicio_atividade"].head())

0   NaT
1   NaT
2   NaT
3   NaT
4   NaT
Name: data_situacao_especial, dtype: datetime64[ns]
0   2023-06-15
1   2017-01-05
2   2017-01-18
3   2021-03-12
4   2017-01-18
Name: data_situacao, dtype: datetime64[us]
0   2017-01-17
1   2017-01-05
2   2017-01-18
3   2017-01-18
4   2017-01-18
Name: data_inicio_atividade, dtype: datetime64[us]

In [116]:
print("Detalhamento CNAE: \n ")
df_cnae.info()

Detalhamento CNAE:

<class 'pandas.DataFrame'>
RangeIndex: 1359 entries, 0 to 1358
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CodigoCNAE              1359 non-null   int64
 1   Cnae_descricao          1359 non-null   str
 2   Especificidades         97 non-null     str
 3   Complementos            23 non-null     str
 4   detalhamento_adicional  5 non-null      str
 5   Observacao              1 non-null      str
dtypes: int64(1), str(5)
memory usage: 63.8 KB

In [117]:
print("Detalhamento Municipios: \n ")
df_municipios.info()

Detalhamento Municipios:

<class 'pandas.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CódigoMunicipio  5572 non-null   int64
 1   Municipio        5572 non-null   str
dtypes: int64(1), str(1)
memory usage: 87.2 KB

In [118]:
cnaes_alimentacao = [4721102, 5611201, 5611203, 5611205, 5611204, 5620104]

In [127]:
print(df_cnae.columns.tolist())

['codigocnae', 'cnae_descricao', 'especificidades', 'complementos', 'detalhamento_adicional', 'observacao']